import { useSession } from "next-auth/react";
import Head from "next/head";
import EntryPage from "~/components/entryPage";
import Router from "~/components/router";
import { UserDataProvider } from "~/contexts/dataContexts";

export default function Home() {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>SCITE finance</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/scite.ico" />
      </Head>
      <main className="min-w-screen flex h-full min-h-screen flex-col justify-stretch bg-[#264474] px-10 pb-5">
        {sessionData ? (
          <UserDataProvider>
            <Router />
          </UserDataProvider>
        ) : (
          <EntryPage />
        )}
      </main>
    </>
  );
}
